### ISSUE TITLE
Crash on custom heist loading screen.

### ISSUE THREAD

**Issue by LulsCupcake** [simon-wh/PAYDAY-2-BeardLib#17]
Testing out the editor, and Im not certain if the problem is in how my main.xml is formatted or something else. But like the title says, I crash whenever I try and load into a custom heist, whether its through the editor or crimenet.

Currently have no mods on except blt, beardlib, beard lib editor, and the pdmod.
When I crash during the loading screen this is the txt.
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/800560/crash.txt)

This is the file for my custom heist. (excuse the extra main.xml, there for testing reasons)
http://www.mediafire.com/file/hm3lqrji98bo88b/Night_Jewelry.rar

edit: doing a quick test map I get this error 
[crashTestMap.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/800614/crashTestMap.txt)

**Comment by Luffyyy** [comment]
Please don't report editor related issues in BeardLib instead in here > https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/issues
First issue was caused because you tried loading a massunit meanwhile you don't have it(if you removed brush layer from world.world that should've solved it)
Second issue is probably a missing file.
You also got no packages loaded I would recommend waiting for an editor update, it should have better tools to create new levels. especially if you're making a heist that is a modification of another heist.
