### ISSUE TITLE
Map bugs

### ISSUE THREAD

**Issue by Mantastaslol** [simon-wh/PAYDAY-2-BeardLib#351]
Well I wanted to play maps such has bhc+, bhg and shadow raid + but everytime I try to load the maps I crash help

**Comment by MiamiCenterPL** [comment]
It's not a BeardLib issue at all, it's Map fault. You have to check crash.txt for more information on what is causing the crash.
It is located at %localappdata%/PAYDAY 2. Open crash.txt and if you have something related to Out Of Memory - the fix is pretty simple, just lower your graphic settings. If it have `Current thread: FileStreamer` at the bottom - simply set Streaming Chunks to 1024 in PAYDAY 2 settings (Advanced).

Hope that helps :P
