### ISSUE TITLE
Custom music

### ISSUE THREAD

**Issue by STALKER20154** [simon-wh/PAYDAY-2-BeardLib#421]
Custom music stopped working

**Comment by Luffyyy** [comment]
Missing information

**Comment by STALKER20154** [comment]
custom music stopped working in the main menu and in heists, it is there, but it doesn't play

**Comment by kamomeri** [comment]
Same issue.
Old style custom music (like .movie) is unable to play since version 4.4
No crash, just silent.

Here is the log when I start the game and exit immediately.
The menu music has been changed, but it is not playing and is silent.
I used this music mod to reproduce it.(https://modworkshop.net/mod/18328) 
[2021_06_05_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6602194/2021_06_05_log.txt)
