### ISSUE TITLE
Attempting to update mods or access custom achievements crashes game

### ISSUE THREAD

**Issue by ImperatorStorm** [simon-wh/PAYDAY-2-BeardLib#479]
**Describe the crash**
Upon pressing "Update All" or "Custom Achievements" in the beardlib menu, the game crashes

**To Reproduce**
1. open beardlib menu
2. press either "Update All" or "Custom Achievements"
3. crash

**Crashlog**
https://pastebin.com/wDC5hGKx <-- "Update All" crash
https://pastebin.com/npnsQb8y <-- "Custom Achievements" crash

**Comment by Luffyyy** [comment]
Cannot reproduce neither.

Might be some mod causing.

In both situations the crash is weird and *should not* happen generally. 

Update all: all items of that list **should** have a "download" item, this crash makes no sense, afaik we don't create anything other than these item.
Achievements: ~~the 2nd parameter is supposed to be nil, the only way it isn't null is if something is messing with the LocalizationManager:text function to return an additional value, that shouldn't be done as the vanilla function expects a single return value.~~ Caused by recent change to SBLT, I will push a pull request to there.

**Comment by ImperatorStorm** [comment]
Fixed as of [superblt-lua `fdf26bb2`](https://gitlab.com/znixian/payday2-superblt-lua/-/commit/fdf26bb275b564e122abb8fb39847b5b852d1be1).
