### ISSUE TITLE
Custom Heist Music sounds lower quality in-game

### ISSUE THREAD

**Issue by SynthwaveFox** [simon-wh/PAYDAY-2-BeardLib#570]
**Describe the bug**
Using the custom heist music template, the music played in-game sounds like it's missing the low or mid-band of audio, giving songs an almost 'radio'-like effect.

**To Reproduce**
Create a song using the custom heist music template provided on modworkshop. Enter a heist with the song, and the audio quality will not match the files provided for the mod.

Included video of what it sounds like in [Audacity vs Payday](https://streamable.com/bniyeo)

**Comment by segabl** [comment]
BeardLib doesn't do anything to audiofiles, if anything this is an issue with SuperBLT. However, from looking into it it seems to be a random thing that started happening without any changes to the sound library used by SuperBLT so it's really hard to know what exactly causes it, especially since it only seems to happen on some systems.

**Comment by PasswordLost** [comment]
Not sure if this has already been resolved in between closing and now, but if it helps, disabling XAudio's HRTF fixed this completely for me, as described in this Reddit thread.
