### ISSUE TITLE
Crash when loading a specific instance

### ISSUE THREAD

**Issue by Aurimenas** [simon-wh/PAYDAY-2-BeardLib#59]
The game crashes when loading  instance hox_fbi_powerbox
I even tried uninstalling every single other mod, but it did not help.
For solely the powerbox crash, there's a log here I'll upload
[2017_07_26_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1175891/2017_07_26_log.txt)

Bonus: I also noticed the game sometimes crashes upon entering vehicles, is there any reason(I'll for the crash again for the log in a moment lol)?

**Comment by Luffyyy** [comment]
Are you talking about the editor? 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Aurimenas** [comment]
Yes

**Comment by Aurimenas** [comment]
Sorry, may have posted it on the wrong page indeed

**Comment by Luffyyy** [comment]
Yes you should post it here https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor but either way if your crashlog is empty(gives nothing useful) then it's an issue I'm unable to fix because it's really random you should still be able to access the map after a few tries if not then post it there with a crashlog also you're supposed to spawn vehicles using an element

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Aurimenas** [comment]
Thanks, and sorry for the wrong place I put this in again, you can lock, or rather delete this now ;p, I'll go post it on editor page
