### ISSUE TITLE
GitHub Auto Update leaves 'empty' folder

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#642]
**Bug description**
GitHub Auto Update leaves an nearly empty folder (with only the version.txt inside) when updating from one folder name to another (which can happen when updating from MWS release to GitHub commit, or just different GitHub branch)

**To Reproduce**
Have a mod with it's folder name beeing different than the one downloaded from GitHub while updating, and force an update on it. 
Example;
Have a mod called 'BeardLib Editor', the game will download a folder called 'BeardLib-Editor-main' from GitHub, and after the update you'll end up with both of these folders beeing in mods, the 'BeardLib Editor' folder would have only version.txt inside.

**Expected behaviour**
Not having old folder at all.

**Comment by segabl** [comment]
Is this happening with latest release or latest github version? and is there anything in the BLT log when this happens? froom the looks of it the code is supposed to delete the entire folder so it leaving a single file might be some permission issue.

**Comment by MiamiCenterPL** [comment]
It seems like it does delete the old folder, but creates it again with a version.txt file afterwards.
And I am actually using the latest BeardLib and latest SuperBLT.
As for logs - there's nothing usefull in there.

**Comment by segabl** [comment]
pinging @Makowo here since he was the one implementing the github stuff, he might know what's going on there

**Comment by Makowo** [comment]
The way GitHub commit updates work is that it reads/writes the commit hash to version.txt, which it uses to determine if it's updated.

It might be writing the updated version.txt file to the original folder instead of the new one just due to where it is in the execution, or because the folder names are different it doesn't know to put it in the new folder location.

**Comment by Makowo** [comment]
> -- On the side - is it possible to add an `use_local_folder` parameter to the GitHub update, soo it actually uses the very same directory to update to?

You can attempt to do a `use_local_folder` with stuff like `folder_name` and `install_directory`. I can't promise that will work, but I've got no interest in trying to mess with the folder names currently. `use_local_dir` and `use_local_path` should already be active, but due to the way GitHub provides the files, it's the best I can do without trying to change the folder names.
