### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by LMauc** [simon-wh/PAYDAY-2-BeardLib#676]
**Describe the crash**
the game crashes due to lack of memory or derivatives, there can be several causes depending on what the mod needs to load, please see the latest crashlog records

**To Reproduce**
1- Load a couple of mods in mod_overrides that require beardlib,
2- Play some new map while waiting for it to crash
(Please prefer the border crossing map, that will crash when you connect to the game at 98%)

**Crashlog**

[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11929566/crashlog.txt)

**Comment by segabl** [comment]
Out of memory crashes are not caused by BeardLib. The game is limited to around 4GB of memory due to being 32bit and certain mods (especially music mods with dynamic loading off) will take a lot of RAM. To solve these issues make sure dynamic/optimized music load is enabled in BeardLib and CustomOST and if you're stillc rashing turn down your texture quality.

**Comment by LMauc** [comment]
the game crashes without reaching 2gb of ram, despite having already applied the 4gb patch that is no longer necessary in payday 2
